// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS6V1X_t2lrlSTmQli0N9IZMS_2vdeA08',
    appId: '1:29110606374:web:b11780505799f2b34a64e7',
    messagingSenderId: '29110606374',
    projectId: 'alsaqr-f47a1',
    authDomain: 'alsaqr-f47a1.firebaseapp.com',
    storageBucket: 'alsaqr-f47a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyCTsvtnIhZV9C_XrOooCWyLGokLiJKa4',
    appId: '1:29110606374:android:0d3c6e67318c954d4a64e7',
    messagingSenderId: '29110606374',
    projectId: 'alsaqr-f47a1',
    storageBucket: 'alsaqr-f47a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxL51DXPK40JOaFH1LM8-nLMaa9RkmH-E',
    appId: '1:29110606374:ios:bc3e1f932f4095c24a64e7',
    messagingSenderId: '29110606374',
    projectId: 'alsaqr-f47a1',
    storageBucket: 'alsaqr-f47a1.firebasestorage.app',
    iosBundleId: 'com.nijatech.alsaqr',
  );
}
