// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2AMSfVeFGxWbYW4sy1Oc82lpBw3-Ufk',
    appId: '1:428538160428:web:a093e87f95b781c94cb889',
    messagingSenderId: '428538160428',
    projectId: 'sjs-ess',
    authDomain: 'sjs-ess.firebaseapp.com',
    storageBucket: 'sjs-ess.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmbftpCCVZ_uT3VfKFPBCLKALXW5zb14',
    appId: '1:428538160428:android:5f92b3b305c5da414cb889',
    messagingSenderId: '428538160428',
    projectId: 'sjs-ess',
    storageBucket: 'sjs-ess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Qz2zDyGVYqRj3EA__DcfPGqKrt-8bIk',
    appId: '1:428538160428:ios:8d8473281338a18e4cb889',
    messagingSenderId: '428538160428',
    projectId: 'sjs-ess',
    storageBucket: 'sjs-ess.firebasestorage.app',
    iosBundleId: 'com.example.sjs.ess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2AMSfVeFGxWbYW4sy1Oc82lpBw3-Ufk',
    appId: '1:428538160428:web:7cf5e82c32cfab1c4cb889',
    messagingSenderId: '428538160428',
    projectId: 'sjs-ess',
    authDomain: 'sjs-ess.firebaseapp.com',
    storageBucket: 'sjs-ess.firebasestorage.app',
  );
}
